export const questions = [
  "Wat is iets wat de meeste mensen niet over jou weten?",
  "Als je morgen ergens naartoe kon reizen, waar zou dat zijn?",
  "Wat is je favoriete herinnering van vroeger?",
  "Welk talent zou je graag willen hebben?",
  "Wat maakt jou écht blij?",
  "Als je een dag lang iemand anders kon zijn, wie zou dat zijn?",
  "Wat is het grappigste dat je ooit hebt meegemaakt?",
  "Welk boek, film of serie heeft je het meest geraakt?",
  "Wat is je meest onverwachte hobby of interesse?",
  "Als je één regel kon maken die iedereen moet volgen, wat zou dat zijn?",
  "Wat is iets wat je altijd al hebt willen proberen maar nog niet hebt gedaan?",
  "Hoe zag jouw ideale zaterdag eruit als kind?",
  "Wat is de beste les die iemand je ooit heeft geleerd?",
  "Welke superkracht zou je kiezen en waarom?",
  "Wat is iets wat jou altijd aan het lachen maakt?",
  "Als je een restaurant kon openen, wat voor keuken zou het hebben?",
  "Wat is je grootste trots van het afgelopen jaar?",
  "Welk dier past het beste bij jouw persoonlijkheid?",
  "Wat is iets wat je doet dat de meeste mensen raar zouden vinden?",
  "Als je één persoon uit de geschiedenis kon ontmoeten, wie zou dat zijn?",
  "Wat is de mooiste plek die je ooit hebt bezocht?",
  "Welk lied zit altijd in je hoofd?",
  "Wat was je droomberoep als kind?",
  "Als je een tijdmachine had, zou je dan naar het verleden of de toekomst gaan?",
  "Wat is iets kleins wat elke dag beter maakt?",
]
